/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cx_jni_Math */

#ifndef _Included_com_cx_jni_Math
#define _Included_com_cx_jni_Math
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cx_jni_Math
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_cx_jni_Math_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_cx_jni_Math
 * Method:    mul
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_cx_jni_Math_mul
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_cx_jni_Math
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_cx_jni_Math_sub
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_cx_jni_Math
 * Method:    div
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_cx_jni_Math_div
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
